# Generated by Django 4.1.2 on 2022-10-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usergame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
