# Generated by Django 4.1.2 on 2022-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='rate',
            field=models.FloatField(),
        ),
    ]
