# Generated by Django 4.1.2 on 2022-10-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_gameinfo_date_alter_gameinfo_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
